---
# tasks file for docker
- name: Install epel-release
  yum:
    name: epel-release
    state: latest
- name: Install Docker
  yum:
    name: docker
    enablerepo: extras
    state: latest
- name: manage Docker service
  service:
    name: docker
    state: started
    enabled: yes
